### ISSUE TITLE
`-version` edge case 

### ISSUE THREAD

**Issue by RasPhilCo** [oclif/plugin-not-found#30]
`-version` prompts for `version` which is a pseudo-command and not found causing a re-prompt for `version` and turtles all the way down.

**Comment by samrae7** [comment]
Hi @jdxcode I am hitting the same issue as this ^.  Could you explain why 'version' was added to the list of commandIDs [here](https://github.com/oclif/plugin-not-found/commit/56a4f62e911816f0a33242d458acbe446c5cf6b9)? For us it causes an issue because it's then one of the suggestions we get, but we don't have a `version` command, so it goes round in circles like @RasPhilCo is saying

**Comment by mdonnalley** [comment]
This has been fixed in the last major
